#!/usr/bin/env bash

set -euo pipefail

DEFAULT_PYTHON=3.9.1
ROOT="$(git rev-parse --show-toplevel)"

has() {
  type "$1" &>/dev/null
}

echo_ok() {
  echo "✅ $*"
}

if ! has pyenv; then
  echo "🛑 Please install pyenv, and then run the bootstrapper again"
  echo "🛑 See: https://github.com/pyenv/pyenv#installation"
  exit 1
fi

PYTHON_VERSION=$(pyenv versions --bare | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+$' | sort | tail -1)
if [ -z "$PYTHON_VERSION" ]; then
  PYTHON_VERSION="$DEFAULT_PYTHON"
fi

VENV="kitefly-$PYTHON_VERSION"

if pyenv versions | grep "$VENV" &>/dev/null; then
  echo_ok "pyenv exists: $VENV"
else
  pyenv virtualenv "$PYTHON_VERSION" "$VENV"
  echo_ok "created pyenv: $VENV"
fi

cd "$ROOT"
echo "$VENV" > ".python-version"

pip install -r "dev_requirements.txt" | grep -v 'already satisfied' ||:
echo_ok "bootstrapping complete"
