#!/usr/bin/env bash

cd "$(git rev-parse --show-toplevel)"
export PYTHONPATH="src"
cov_report=(--cov-report html)
if [[ "$CI" == "true" ]]; then
    cov_report=(--cov-report term --cov-report xml)
fi
pytest "${cov_report[@]}" --cov ./src/kitefly ./tests -v "$@"
