#!/usr/bin/env bash

export PYTHONPATH="."
cov_report=(--cov-report html)
if [[ "$CI" == "true" ]]; then
    cov_report=(--cov-report term --cov-report xml)
fi
pytest "${cov_report[@]}" --cov ./kitefly ./tests -v "$@"
